# Generated by Django 4.2.4 on 2023-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_photo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pre_value',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
