# Generated by Django 4.2.4 on 2023-09-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_photo_app', '0003_info_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info_img',
        ),
    ]
